config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :tasks, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @categories = Category.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :authenticate_user!
  def new
    @categories = Category.all
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category
    if @task.save
      redirect_to root_path
      flash[:notice] = "Task created"
    else
      redirect_to root_path
      flash[:notice] = "Please try again"
    end
  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.all

  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
    flash[:notice] = "Task edited"
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end


  private

  def task_params
    params.permit(:title, :deadline, :description)
  end

  def category_params
    params.require(:Category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1 class="text-center mb-4">Welcome to my todolist app</h1>
<%= render 'layouts/task_form'  %>
<div class="container">
  <ul>
  <% @categories.each do  |category|%>
  <li><%= category.title  %></li>
  <div class="card">
    <ul>
      <% category.tasks.each do |task|  %>
      <li>
        <%= task.title  %>
        <% unless task.deadline.nil? %>
          , to read: <%= task.deadline.strftime('%D')  %>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
  </ul>
</div>

<div class="container">
  <div class="row">
    <% @tasks.each do |task|  %>
      <div class="card col-3">
        <% unless task.image.nil? %>
          <%= image_tag task.image, class: "rounded-circle" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to "Sandbox App", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <% unless user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
      
    </ul>
        <img class="rounded-circle" height="50px" width="50px" src="http://digitalspyuk.cdnds.net/17/25/320x320/square-1498216547-avatar-neytiri.jpg">
  </div>
</nav>

app/views/layouts/_task_form.html.erb
<div class="container">

  <div class="row ml-3">
      <div class="offset-md-3 col-md-6 offset-md-3">
          <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form")  do %>
              <div class="form-group">
                  <%= label_tag "Task", nil, class: "form-label" %>
                  <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Deadline", nil, class: "form-label" %>
                  <%= date_field_tag :deadline, nil, class: "form-control" %>

              </div>
              <div class="form-group">
                  <%= label_tag "Category", nil, class: "form-label" %>
                  <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
              </div>

              <div class="text-center">
                  <%= submit_tag("Create task", class: "btn btn-start-order") %>
              </div>
          <%end%>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task_list.html.erb
<ul>
  <% @tasks.each do |task|  %>
    <li>
      <%= task.title %>,
      "Deadline : " <%=  task.deadline.strftime("%D")  %>
       <%= link_to "Edit this task", edit_task_path(task) %>
    </li>
  <% end %>
</ul>

app/views/tasks/edit.html.erb
<h4>Edit your task</h4>
<%= form_tag(task_path, method: "put") do %>
  <div class="form-group">
      <%= label_tag("Your task:") %>
      <%= text_field_tag(:title, @task.title) %>
  </div>

  <div class="form-group">
    <%= label_tag("When is it due for ?") %>
    <%= date_field_tag(:deadline, @task.deadline)  %>
  </div>
    <%= submit_tag("Edit task", class: "btn btn-info") %>
<% end %>
<%= link_to "Delete this task", task_path(@task), method: :delete, class: "btn btn-danger" %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <%= render 'task_list'  %>

<% end %>

<%= link_to "Create a new task", new_task_path, class: "btn btn-info"  %>

app/views/tasks/new.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/task_form'  %>
<% end %>